apiVersion: v1
kind: Service
metadata:
  name: dota2metalab-api
  namespace: {{ .Values.global.namespace }}
spec:
  type: ClusterIP
  selector:
    app: dota2metalab-api
  ports:
    - port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}