apiVersion: apps/v1
kind: Deployment
metadata:
  name: dota2metalab-api
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  progressDeadlineSeconds: 1200
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: dota2metalab-api
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        app: dota2metalab-api
    spec:
      serviceAccountName: dota2metalab-api
      containers:
        - name: api
          image: {{ .Values.image.repository }}-api:{{ .Values.image.api.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.api.port }}
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:{{ .Values.mongodb.port }}
            - name: PYTHONPATH
              value: /app
            - name: S3_BUCKET
              value: {{ .Values.s3.bucket }}
            - name: S3_PREFIX
              value: {{ .Values.s3.prefix }}
          resources:
            requests:
              cpu: {{ .Values.api.resources.requests.cpu | quote }}
              memory: {{ .Values.api.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.api.resources.limits.cpu | quote }}
              memory: {{ .Values.api.resources.limits.memory | quote }}
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.api.port }}
            initialDelaySeconds: 300
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.api.port }}
            initialDelaySeconds: 300
            periodSeconds: 5
            failureThreshold: 3