apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.models.persistence.size }}
  storageClassName: {{ .Values.models.persistence.storageClassName }}
