apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
  annotations:
    "argocd.argoproj.io/sync-wave": "0"
spec:
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        storageClassName: {{ .Values.mongodb.persistence.storageClassName }}
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.mongodb.persistence.size }}
