apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: {{ .Values.global.namespace }}
  annotations:
    "argocd.argoproj.io/sync-wave": "0"
spec:
  type: ClusterIP
  selector:
    app: mongodb
  ports:
    - port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}