apiVersion: v1
kind: ServiceAccount
metadata:
  name: dota2metalab-api
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- if eq .Values.cloud "azure" }}
    azure.workload.identity/client-id: {{ .Values.azureIdentity.clientId }}
    {{- else }}
    eks.amazonaws.com/role-arn: {{ .Values.irsa.roleArn }}
    {{- end }}
    "argocd.argoproj.io/sync-wave": "2"
  {{- if eq .Values.cloud "azure" }}
  labels:
    azure.workload.identity/use: "true"
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dota2metalab-trainer
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- if eq .Values.cloud "azure" }}
    azure.workload.identity/client-id: {{ .Values.azureIdentity.clientId }}
    {{- else }}
    eks.amazonaws.com/role-arn: {{ .Values.irsa.roleArn }}
    {{- end }}
    "argocd.argoproj.io/sync-wave": "2"
  {{- if eq .Values.cloud "azure" }}
  labels:
    azure.workload.identity/use: "true"
  {{- end }}