apiVersion: v1
kind: ServiceAccount
metadata:
  name: dota2metalab-api
  namespace: {{ .Values.global.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.roleArn }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dota2metalab-trainer
  namespace: {{ .Values.global.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.roleArn }}