apiVersion: batch/v1
kind: Job
metadata:
  name: dota2metalab-trainer
  namespace: {{ .Values.global.namespace }}
  annotations:
    "argocd.argoproj.io/sync-wave": "2"
    "argocd.argoproj.io/hook": "Sync"
    "argocd.argoproj.io/hook-delete-policy": "HookSucceeded"
    "argocd.argoproj.io/sync-options": "Replace=true"
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: dota2metalab-trainer
      containers:
        - name: trainer
          image: {{ .Values.image.repository }}-trainer:{{ .Values.image.trainer.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGO_URI
              value: mongodb://mongodb:{{ .Values.mongodb.port }}
            - name: PYTHONPATH
              value: /app
            - name: S3_BUCKET
              value: {{ .Values.s3.bucket }}
            - name: S3_PREFIX
              value: {{ .Values.s3.prefix }}
            - name: API_URL
              value: http://dota2metalab-api:{{ .Values.api.port }}
      restartPolicy: Never