apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dota2-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/rinavillaruz/dota2metalab-infra
    targetRevision: main
    path: argocd-apps

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true