# Global settings
global:
  namespace: dota2metalab-prod

# MongoDB settings
mongodb:
  persistence:
    size: 20Gi

# API settings
api:
  replicas: 3

# Models storage
models:
  persistence:
    size: 2Gi

ingress:
  enabled: true
  host: dota2metalab.com

irsa:
  roleArn: "arn:aws:iam::643297135135:role/dota2metalab-s3-models"