# Global settings
global:
  namespace: dota2metalab

# Image settings
image:
  repository: rinavillaruz/dota2metalab
  pullPolicy: Always
  api:
    tag: latest
  fetcher:
    tag: latest
  trainer:
    tag: latest

# MongoDB settings
mongodb:
  replicas: 1
  image: mongo:7.0
  port: 27017
  persistence:
    size: 5Gi
    storageClassName: gp2

# API settings
api:
  replicas: 1
  port: 8080

# Models storage
models:
  persistence:
    size: 1Gi
    storageClassName: gp2