# Global settings
global:
  namespace: dota2metalab-dev
# Image settings — GitHub Actions updates each tag independently
# Only the image that was rebuilt will have its tag updated
image:
  api:
    tag: 20260607110708-ba8f3ba
  fetcher:
    tag: 20260607124916-46a884b
  trainer:
    tag: 20260607124916-46a884b
# MongoDB settings
mongodb:
  persistence:
    size: 2Gi
    storageClassName: standard
# Models storage
models:
  persistence:
    size: 500Mi
    storageClassName: standard
ingress:
  host: dev.dota2metalab.com
irsa:
  roleArn: "arn:aws:iam::643297135135:role/dota2metalab-s3-models"
