# Global settings
global:
  namespace: dota2metalab-staging
# MongoDB settings
mongodb:
  persistence:
    size: 5Gi
# API settings
api:
  replicas: 1
# Models storage
models:
  persistence:
    size: 2Gi
ingress:
  enabled: true
  host: staging.dota2metalab.com
image:
  api:
    tag: 20260607173352-9967544
  fetcher:
    tag: 20260607132607-2da2541
  trainer:
    tag: 20260607132607-2da2541
irsa:
  roleArn: "arn:aws:iam::643297135135:role/dota2metalab-s3-models"

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilization: 70
