# Global settings
global:
  namespace: dota2metalab-staging

# MongoDB settings
mongodb:
  persistence:
    size: 5Gi

# API settings
api:
  replicas: 1

# Models storage
models:
  persistence:
    size: 2Gi

ingress:
  host: staging.dota2metalab.com