# Global settings
global:
  namespace: dota2metalab-dev

# Image settings — GitHub Actions will update this tag with SHA
image:
  tag: 31f7b7434ba88ed1e6ba9af8c9b220faff7f241c

# MongoDB settings
mongodb:
  persistence:
    size: 2Gi
    storageClassName: standard

# Models storage
models:
  persistence:
    size: 500Mi
    storageClassName: standard