configs:
  params:
    server.insecure: true

server:
  service:
    type: ClusterIP
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

controller:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

repoServer:
  replicas: 1
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

redis:
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: false 

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilization: 70